name: Cache Prime Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: prime-cache-eef71f2
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/myapp
          key: cache-eef71f2

      - name: Check cache result
        run: echo "Cache hit result: ${{ steps.cache-step.outputs.cache-hit }}"
